### ISSUE TITLE
how to use decompression module

### ISSUE THREAD

**Issue by Brillise** [fpgasystems/caribou#1]
Hi Istvan
I thought **nukv_Decompress.v** file is related with data decompression, which is rarely mentioned in the paper. And this file is also not Instantiated by the top module in the project. How should I make use of it to realize the decompression functionality?
Thank you!

**Comment by zistvan** [comment]
Hi Brillise,

We tried to simplify the toplevel a little bit for the demo we made for the Xilinx Open Hardware Contest and decided not to include decompression as it complicates clients to some extent. We are in the middle of a busy period, but adding more toplevel options (e.g. compute+decompression, or without compute at all) is part of our plans. I'd say check back later, or I can also ping you if you wish, when we have one ready for sharing.

**Comment by Brillise** [comment]
Hi Istvan
It will be very nice of you for sharing code with decompression. You can send e-mail to me or just upload to the github.
Thank you so much!
